name: 自动解密 API
on:
  workflow_dispatch: # 支持手动点击运行

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: 安装 Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16
      - name: 执行解密脚本
        run: node decrypt_api.js
      - name: 同步明文到仓库
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add decoded_api.json
          git commit -m "update: 同步明文文件" || exit 0
          git push
